class Food {
  String name;
  double price;
  String category;
  double rating;
  String description;
  String image;
  int? qty;
  Food({
    required this.name,
    required this.price,
    required this.category,
    required this.rating,
    required this.description,
    required this.image,
    this.qty,
  });
}

List<Food> foodList = [
  Food(
    name: "Cheese Pizza",
    price: 8.99,
    category: "pizza",
    rating: 4.6,
    description: "Classic cheese pizza with mozzarella",
    image: "assets/images/food/cheese_pizza.png",
  ),
  Food(
    name: "Pepperoni Pizza",
    price: 9.99,
    category: "pizza",
    rating: 4.8,
    description: "Pepperoni pizza with extra cheese",
    image: "assets/images/food/pizza_pepperoni.png",
  ),
  Food(
    name: "Beef Burger",
    price: 5.99,
    category: "burger",
    rating: 4.5,
    description: "Juicy beef burger with lettuce and cheese",
    image: "assets/images/food/burger_beef.png",
  ),
  Food(
    name: "Chicken Burger",
    price: 5.49,
    category: "burger",
    rating: 4.4,
    description: "Crispy chicken burger with sauce",
    image: "assets/images/food/burger_chicken.png",
  ),
  Food(
    name: "Chocolate Cake",
    price: 4.99,
    category: "cake",
    rating: 4.7,
    description: "Rich chocolate cake with soft cream",
    image: "assets/images/food/cake_chocolate.png",
  ),
  Food(
    name: "Cheese Cake",
    price: 5.49,
    category: "cake",
    rating: 4.6,
    description: "Creamy cheesecake with biscuit base",
    image: "assets/images/food/cake_cheese.png",
  ),
  Food(
    name: "Orange Juice",
    price: 2.99,
    category: "drink",
    rating: 4.3,
    description: "Fresh orange juice served cold",
    image: "assets/images/food/drink_orange.png",
  ),
  Food(
    name: "Iced Lemon Tea",
    price: 2.49,
    category: "drink",
    rating: 4.2,
    description: "Refreshing iced lemon tea",
    image: "assets/images/food/drink_lemon.png",
  ),
  Food(
    name: "Hot Coffee",
    price: 3.49,
    category: "coffee",
    rating: 4.5,
    description: "Fresh brewed hot coffee",
    image: "assets/images/food/coffee_hot.png",
  ),
  Food(
    name: "Iced Latte",
    price: 3.99,
    category: "coffee",
    rating: 4.6,
    description: "Smooth iced latte with milk",
    image: "assets/images/food/coffee_latte.png",
  ),
  Food(
    name: "BBQ Chicken Pizza",
    price: 10.49,
    category: "pizza",
    rating: 4.7,
    description: "BBQ chicken pizza with smoky flavor",
    image: "assets/images/food/pizza_bbq.png",
  ),
  Food(
    name: "Double Beef Burger",
    price: 7.99,
    category: "burger",
    rating: 4.8,
    description: "Double beef patty with cheese",
    image: "assets/images/food/burger_double.png",
  ),
  Food(
    name: "Grilled Chicken",
    price: 6.99,
    category: "chicken",
    rating: 4.6,
    description: "Grilled chicken with special sauce",
    image: "assets/images/food/chicken_grilled.png",
  ),
  Food(
    name: "Spaghetti Bolognese",
    price: 6.49,
    category: "pasta",
    rating: 4.5,
    description: "Spaghetti with beef bolognese sauce",
    image: "assets/images/food/spaghetti.png",
  ),
  Food(
    name: "Seafood Fried Rice",
    price: 5.99,
    category: "rice",
    rating: 4.4,
    description: "Fried rice with shrimp and squid",
    image: "assets/images/food/fried_rice_seafood.png",
  ),
  Food(
    name: "Green Salad",
    price: 3.99,
    category: "salad",
    rating: 4.3,
    description: "Fresh green salad with dressing",
    image: "assets/images/food/salad_green.png",
  ),
  Food(
    name: "Strawberry Cake",
    price: 5.99,
    category: "cake",
    rating: 4.7,
    description: "Soft strawberry cake with cream",
    image: "assets/images/food/cake_strawberry.png",
  ),
  Food(
    name: "Vanilla Ice Cream",
    price: 2.49,
    category: "dessert",
    rating: 4.4,
    description: "Vanilla ice cream scoop",
    image: "assets/images/food/icecream_vanilla.png",
  ),
  Food(
    name: "Cappuccino",
    price: 3.79,
    category: "coffee",
    rating: 4.6,
    description: "Hot cappuccino with milk foam",
    image: "assets/images/food/coffee_cappuccino.png",
  ),
  Food(
    name: "Iced Matcha Latte",
    price: 4.29,
    category: "drink",
    rating: 4.5,
    description: "Cold matcha latte with milk",
    image: "assets/images/food/drink_matcha.png",
  ),
];
